name: Log ISS Location Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC
  workflow_dispatch:

jobs:
  collect-iss-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch ISS location data
        run: |
          python3 -c "
import requests
import json
import datetime

url = 'http://api.open-notify.org/iss-now.json'
response = requests.get(url)
try:
    data = response.json()
    with open('iss-location.jsonl', 'a') as f:
        f.write(json.dumps(data) + '\n')
except Exception as e:
    print('Failed to get valid JSON:', e)
"

      - name: Commit and push data
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add iss-location.jsonl
          git commit -m "Update ISS position data [skip ci]" || echo "No changes to commit"
          git push
