name: Log ISS Location Data Daily

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  collect-iss-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Fetch ISS location data
      run: |
        python3 -c "
import requests
data = requests.get('http://api.open-notify.org/iss-now.json').text
with open('iss-location.jsonl', 'a') as f:
    f.write(data + '\n')
"

    - name: Commit and push changes
      run: |
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git add iss-location.jsonl
        git commit -m 'Update ISS position data [skip ci]' || echo 'No changes to commit'
        git push
